### ISSUE TITLE
add Standaard Energie eFactuur extension

### ISSUE THREAD

**Issue by EricAriensGit** [UblSharp/UblSharp#9]
Hi,

Is it possible to add the Standaard Energie eFactuur extension.
https://energie-efactuur.nl/

Regards
Eric

**Comment by remcoros** [comment]
I see there's an xsd available, so that should not be too hard.

![image](https://user-images.githubusercontent.com/130373/33185533-a7a30c48-d083-11e7-8aae-b29a55f15a1b.png)

This would be a good candidate for a separate package though (e.g. UblSharp.EEFactuur), to keep UblSharp clean of domain-specific extension types.

The codegen tool is currently not easily consumable, so needs some refactorings and make it into a tool/library trough nuget or something. It's on my wishlist, but haven't run into it yet myself :)

In the meantime, you could clone/copy this repo and tweak it to you're liking. Run the generator, copy/paste the output of the additional classes and use those in your project.

Have a look at this: https://github.com/UblSharp/UblSharp/blob/master/src/UblSharp.Generator/Program.cs#L21

And see what happens if you drop the xsd from e-efactuur in the resources folder.

**Comment by remcoros** [comment]
A nuget package for SEeF is now available here: https://www.nuget.org/packages/UblSharp.SEeF/
